#!/bin/bash
# Copyright (c) 2013 Jason W Ryan
# The MIT License (MIT) http://opensource.org/licenses/MIT
# Modifications by Niels Robin-Aubertin

# colours
lt=$'\e[1;36m' # light cyan
dk=$'\e[0;36m' # dark cyan
tx=$'\e[1;32m' # green text
ec=$'\e[0m'

# details
machine=$(</proc/sys/kernel/hostname)
arch=$(uname -m)
mykernel=$(uname -r)
mycpu=$(awk '/cpu/ {flag=1} /!/ {flag=0} flag && /Intel/ {sub(/\(TM\)/,""); print $5,$6,$7,$8;exit}' /proc/cpuinfo)
myuptime=$(awk -F"[, ]" '{ if (NF==17) print $4; else print $4,$5 }' <(uptime))
myshell=$(ps -p `ps -p $$ -o ppid=` | sed -n '2p' | sed 's/.*\s\(.*\)$/\1/')
myterm=$(echo $TERM)
myedit=$(echo ${EDITOR##*/})
mybrowser=$(echo ${BROWSER##*/})
mymultiplexer=$(echo ${MULTIPLEXER##*/})


# ASCII goodness…
  cat <<EOF
${dk}                 +
                 #                 ${tx}Machine:${ec} ${machine}${dk}
                ###                ${tx}Architecture:${ec} ${arch}${dk}
               #####               ${tx}Kernel:${ec} ${mykernel}${dk}
               ######              ${tx}CPU:${ec} ${mycpu}${dk}
              ; #####;             ${tx}Uptime:${ec} ${myuptime}${dk}
             +##.#####             
            +##########            
           #############;          ${tx}Shell:${ec} ${myshell^}${dk}
          ###############+         ${tx}Terminal:${ec} ${myterm^}${dk}
         #######   #######         ${tx}Multiplexer:${ec} ${mymultiplexer^}${dk}
       .######;     ;###;\`.        ${tx}Editor:${ec} ${myedit^}${dk} 
      .#######;     ;#####.        ${tx}Browser:${ec} ${mybrowser^}${dk}
      #########.   .########\`
     ######'           '######
    ;####                 ####;
    ##'                     '##
   #'                         \`#
  '                            \`${ec}

EOF
